### ISSUE TITLE
Replace Buddy with GitHub Actions

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-newsletter-builder#167]
## Description

Upgrading the project from Buddy to GitHub actions will ensure parity with other Alley projects, reduce costs, and allow leveraging 'shared' common workflows or actions.

## Acceptance Criteria

- All CI/CD pipelines (eg. PR tests or deployment) are replaced by equivalent GitHub actions
- Any secrets are recreated or moved to GitHub secrets (environment or otherwise)
- Buddy disabled for the project

**Comment by benpbolton** [comment]
Interesting. @kevinfodness "most" of wp-newsletter-builder seems to [use github actions already](https://github.com/alleyinteractive/wp-newsletter-builder/tree/develop/.github/workflows) (the older reusable 'workflow' style instead of the 'action' style, but... it can work here). 

I do see a buddy.yml... and I don't see our typical 'general' tests in the repo.

Do we kindof want to consolidate/refresh the existing github action tests  (consolidate to a single pr-tests or what-have-you that checks node + php/composer stuffs) or just leave well enough alone, add a general tests to capture git ignored files, etc... and remove buddy?

**Comment by kevinfodness** [comment]
Yeah, it seems like Buddy isn't used at all. For this phase of work, let's remove the Buddy config, make sure the project is deleted in Buddy, and update the branch protection rules to require the GitHub Actions to pass. We can take another pass at updating our configs in the future to use the new action workflow (other projects are going to be affected by this as well, and I'd rather focus on spinning down Buddy right now, then come back and handle further standardization with a wider net later).
